### ISSUE TITLE
Build fails on opensuse 42.3

### ISSUE THREAD

**Issue by M-Stenzel** [iridium-browser/tracker#345]
Hi team,

I am still running this OS version and would like to use the latest version of Iridium, however, build fails here:

[5500/49832] python3 ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/node/node.py ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/node_modules/rollup/dist/bin/rollup --silent --config ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/scripts/build/rollup.config.js --input gen/third_party/devtools-frontend/src/front_end/panels/timeline/components/components.prebundle.js --file gen/third_party/devtools-frontend/src/front_end/panels/timeline/components/components.js --configDCHECK
FAILED: gen/third_party/devtools-frontend/src/front_end/panels/timeline/components/components.js 
python3 ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/node/node.py ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/node_modules/rollup/dist/bin/rollup --silent --config ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/scripts/build/rollup.config.js --input gen/third_party/devtools-frontend/src/front_end/panels/timeline/components/components.prebundle.js --file gen/third_party/devtools-frontend/src/front_end/panels/timeline/components/components.js --configDCHECK
Traceback (most recent call last):
  File "../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/node/node.py", line 43, in <module>
    RunNode(sys.argv[1:])
  File "../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/node/node.py", line 38, in RunNode
    raise RuntimeError('Command \'%s\' failed\n%s' % (' '.join(cmd), err))
RuntimeError: Command '../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/node/linux/node-linux-x64/bin/node ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/node_modules/rollup/dist/bin/rollup --silent --config ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/scripts/build/rollup.config.js --input gen/third_party/devtools-frontend/src/front_end/panels/timeline/components/components.prebundle.js --file gen/third_party/devtools-frontend/src/front_end/panels/timeline/components/components.js --configDCHECK' failed
[!] (plugin minify-html-template-literals) TypeError: result.matchAll is not a function
gen/third_party/devtools-frontend/src/front_end/panels/timeline/components/WebVitalsTimeline.js
TypeError: result.matchAll is not a function
    at Object.minifyHTML (/usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/node_modules/minify-html-literals/src/strategy.ts:145:41)
    at Object.minifyHTML (/usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/scripts/build/rollup.config.js:80:37)
    at templates.forEach.template (/usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/node_modules/minify-html-literals/src/minifyHTMLLiterals.ts:322:24)
    at Array.forEach (<anonymous>)
    at Object.minifyHTMLLiterals (/usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/node_modules/minify-html-literals/src/minifyHTMLLiterals.ts:297:13)
    at Object.transform (/usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/node_modules/rollup-plugin-minify-html-template-literals/dist/index.js:15:47)
    at Promise.resolve.then (/usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/node_modules/rollup/dist/shared/rollup.js:20197:25)

[5501/49832] python3 ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/third_party/typescript/ts_library.py --tsconfig_output_location gen/third_party/devtools-frontend/src/front_end/ui/components/adorners/devtools_entrypoint-bundle-tsconfig-tsconfig.json --deps ./adorners-tsconfig.json ./css_files-tsconfig.json --front_end_directory gen/third_party/devtools-frontend/src/front_end/ui/components/adorners --sources gen/third_party/devtools-frontend/src/front_end/ui/components/adorners/adorners.prebundle.ts
[5502/49832] python3 ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/third_party/typescript/ts_library.py --tsconfig_output_location gen/third_party/devtools-frontend/src/front_end/ui/components/linkifier/linkifier-tsconfig.json --deps ../../../models/bindings/bundle-tsconfig.json ../render_coordinator/bundle-tsconfig.json ../../lit-html/bundle-tsconfig.json ../helpers/bundle-tsconfig.json --front_end_directory ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/front_end/ui/components/linkifier --reset_timestamps --sources ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/front_end/ui/components/linkifier/LinkifierImpl.ts ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/devtools-frontend/src/front_end/ui/components/linkifier/LinkifierUtils.ts
[5503/49832] python3 ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/third_party/blink/renderer/bindings/scripts/generate_bindings.py --web_idl_database gen/third_party/blink/renderer/bindings/web_idl_database.pickle --root_src_dir ../../usr/src/packages/BUILD/iridium-browser-2021.10.95/ --root_gen_dir gen --output_reldir core=third_party/blink/renderer/bindings/core/v8/ --output_reldir modules=third_party/blink/renderer/bindings/modules/v8/ --format_generated_files enumeration callback_function callback_interface dictionary interface namespace typedef union
ninja: build stopped: subcommand failed.
error: Bad exit status from /var/tmp/rpm-tmp.EdqLak (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.EdqLak (%build)

Any ideas how to proceed? 

Martin.

**Comment by jengelh** [comment]
Closing because 42.x is (by now) out of date and removed.
